services:
  app:
    build:
      context: .
    image: go-echo-sample:latest
    container_name: go-echo-sample
    ports:
      - "127.0.0.1:8080:8080"
    restart: always
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0.14
    container_name: mongo
    ports:
      - "127.0.0.1:27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "127.0.0.1:8081:8081"
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
      - mongo
